[config]
default_to_workspace = false

# Utils
[tasks.update]
command = "cargo"
args = ["update"]

[tasks.fmt]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--all"]

[tasks.clippy]
install_crate = "clippy"
command = "cargo"
args = ["clippy", "--all"]
dependencies = ["fmt"]

[tasks.outdated]
install_crate = "outdated"
command = "cargo"
args = ["outdated", "-wR"]
dependencies = ["update"]

[tasks.sweep]
install_crate = "sweep"
command = "cargo"
args = ["sweep", "-r", "-t", "1"]

[tasks.test]
command = "cargo"
args = ["test", "--all"]
dependencies = ["update"]
